using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Tilemaps;

namespace GloomCraft.Dungeon
{
    /// <summary>
    /// [DEPRECATED] Legacy dungeon builder - use MapInitializationManager instead.
    /// This class is kept for backward compatibility with existing scenes.
    /// 
    /// New architecture:
    /// - MapInitializationManager (orchestrator)
    /// - TilemapDungeonRenderer (rendering with object pooling)
    /// - EntitySpawner (enemies/furniture with pooling)
    /// - DungeonConfig (ScriptableObject configuration)
    /// </summary>
    [System.Obsolete("Use MapInitializationManager with TilemapDungeonRenderer and EntitySpawner instead.")]
    public sealed class UnityDungeonTilemapBuilder : MonoBehaviour
    {
        [Header("=== NEW SYSTEM (Recommended) ===")]
        [Tooltip("Enable to use new optimized system with pooling")]
        [SerializeField] private bool useNewSystem = false;
        [SerializeField] private MapInitializationManager mapManager;
        [SerializeField] private DungeonConfig dungeonConfig;
        
        [Header("=== LEGACY SETTINGS ===")]
        [SerializeField] private int columns = 30;
        [SerializeField] private int rows = 30;
        [SerializeField] private int minRoom = 7;
        [SerializeField] private int maxRoom = 15;
        [SerializeField] private int density = 30;
        [SerializeField] private int seed = 0;
        [SerializeField] private bool useSeed = false;

        [Header("Tilemap refs")]
        [SerializeField] private Grid grid;
        [SerializeField] private Tilemap floorTilemap;
        [SerializeField] private Tilemap wallTilemap;

        [Header("Tileset (microStudio dungeon/tileset frames)")]
        [Tooltip("Config asset generated by MicroStudioImportConfigurator for sprites/dungeon-tileset.png.")]
        [SerializeField] private DungeonTilesetConfig tilesetConfig;
        [SerializeField] private int floorFrameIndex = 0;

        [Header("Wall Overlays (microStudio-style multi-frame rendering)")]
        [Tooltip("Container for wall overlay sprites. Auto-created if null.")]
        [SerializeField] private Transform wallOverlayContainer;
        [Tooltip("Sorting layer name for wall overlays (should be above walls tilemap).")]
        [SerializeField] private string overlaySortingLayer = "Default";
        [Tooltip("Sorting order offset for overlays.")]
        [SerializeField] private int overlaySortingOrder = 1;

        [Header("Spawn")]
        [SerializeField] private Transform player;
        
        [Header("Furnishing (optional)")]
        [SerializeField] private DungeonFurnisher2D furnisher;

        public DungeonGenerator2D.Result LastResult { get; private set; }
        
        /// <summary>
        /// Get the new MapInitializationManager if using new system
        /// </summary>
        public MapInitializationManager MapManager => mapManager;

        private readonly Dictionary<int, Tile> _tileCache = new();
        private readonly List<GameObject> _overlayInstances = new();

        [ContextMenu("Generate Dungeon Now")]
        public void GenerateNow()
        {
            // NEW SYSTEM: Delegate to MapInitializationManager
            if (useNewSystem && TryUseNewSystem())
            {
                return;
            }
            
            // LEGACY: Original implementation
            EnsureTilemaps();
            EnsureOverlayContainer();

            var result = DungeonGenerator2D.Generate(columns, rows, minRoom, maxRoom, density, useSeed ? seed : null);
            LastResult = result;
            Build(result.Map);

            if (player != null)
            {
                // microStudio centers at (column+0.5)*16. In Unity, we treat 1 tile == 1 unit.
                var p = new Vector3(result.Map.Start.x + 0.5f, result.Map.Start.y + 0.5f, player.position.z);
                player.position = p;
            }

            if (furnisher == null) furnisher = GetComponent<DungeonFurnisher2D>();
            if (furnisher != null)
            {
                furnisher.Furnish(result);
            }
        }

        private void EnsureTilemaps()
        {
            if (grid == null) grid = FindFirstObjectByType<Grid>();

            if (grid == null)
            {
                var go = new GameObject("Grid");
                grid = go.AddComponent<Grid>();
                grid.cellSize = Vector3.one; // 1 unit per tile
            }

            if (floorTilemap == null)
            {
                var go = new GameObject("Floor", typeof(Tilemap), typeof(TilemapRenderer));
                go.transform.SetParent(grid.transform, false);
                floorTilemap = go.GetComponent<Tilemap>();
            }

            if (wallTilemap == null)
            {
                var go = new GameObject("Walls", typeof(Tilemap), typeof(TilemapRenderer), typeof(TilemapCollider2D), typeof(CompositeCollider2D), typeof(Rigidbody2D));
                go.transform.SetParent(grid.transform, false);
                wallTilemap = go.GetComponent<Tilemap>();

                var rb = go.GetComponent<Rigidbody2D>();
                rb.bodyType = RigidbodyType2D.Static;

                var tmc = go.GetComponent<TilemapCollider2D>();
                tmc.compositeOperation = Collider2D.CompositeOperation.Merge;

                var cc = go.GetComponent<CompositeCollider2D>();
                cc.geometryType = CompositeCollider2D.GeometryType.Polygons;
                cc.generationType = CompositeCollider2D.GenerationType.Synchronous;
            }
        }

        private void EnsureOverlayContainer()
        {
            if (wallOverlayContainer == null)
            {
                var go = new GameObject("WallOverlays");
                go.transform.SetParent(grid != null ? grid.transform : transform, false);
                wallOverlayContainer = go.transform;
            }
        }

        private void Build(DungeonMap map)
        {
            // Clear previous overlays
            foreach (var overlay in _overlayInstances)
            {
                if (overlay != null) DestroyImmediate(overlay);
            }
            _overlayInstances.Clear();

            floorTilemap.ClearAllTiles();
            wallTilemap.ClearAllTiles();

            for (var r = 0; r < map.Rows; r++)
            for (var c = 0; c < map.Columns; c++)
            {
                var cell = map.Get(c, r);

                if (cell != DungeonCell.Wall)
                {
                    floorTilemap.SetTile(new Vector3Int(c, r, 0), GetTile(floorFrameIndex));
                }
                else
                {
                    // Render walls by bitmask: multiple frames can be overlaid in microStudio.
                    // We place the first frame in the tilemap (for collider), then spawn overlays for the rest.
                    var frames = DungeonWallBitmask.GetWallFrameIndexes(map, c, r);
                    
                    if (frames.Count > 0)
                    {
                        // First frame goes into tilemap (for collider)
                        wallTilemap.SetTile(new Vector3Int(c, r, 0), GetTile(frames[0]));

                        // Remaining frames spawn as SpriteRenderer overlays (microStudio-style)
                        for (var i = 1; i < frames.Count; i++)
                        {
                            var frameIndex = frames[i];
                            if (frameIndex < 0 || tilesetConfig == null || tilesetConfig.frames == null || frameIndex >= tilesetConfig.frames.Length) continue;

                            var overlayGo = new GameObject($"WallOverlay_{c}_{r}_{i}");
                            overlayGo.transform.SetParent(wallOverlayContainer, false);
                            
                            // microStudio centers at (column+0.5)*16, Unity uses 1 unit per tile
                            overlayGo.transform.position = new Vector3(c + 0.5f, r + 0.5f, 0);

                            var sr = overlayGo.AddComponent<SpriteRenderer>();
                            sr.sprite = tilesetConfig.frames[frameIndex];
                            sr.sortingLayerName = overlaySortingLayer;
                            sr.sortingOrder = overlaySortingOrder + i; // Higher frames render on top

                            _overlayInstances.Add(overlayGo);
                        }
                    }
                }
            }
        }

        private Tile GetTile(int frameIndex)
        {
            if (frameIndex < 0) return null;
            if (_tileCache.TryGetValue(frameIndex, out var cached)) return cached;
            if (tilesetConfig == null || tilesetConfig.frames == null || frameIndex >= tilesetConfig.frames.Length) return null;

            var t = ScriptableObject.CreateInstance<Tile>();
            t.sprite = tilesetConfig.frames[frameIndex];
            _tileCache[frameIndex] = t;
            return t;
        }
        
        /// <summary>
        /// Try to use the new MapInitializationManager system
        /// </summary>
        private bool TryUseNewSystem()
        {
            if (mapManager == null)
            {
                mapManager = FindFirstObjectByType<MapInitializationManager>();
            }
            
            if (mapManager == null)
            {
                Debug.LogWarning("[UnityDungeonTilemapBuilder] useNewSystem=true but no MapInitializationManager found. Falling back to legacy.");
                return false;
            }
            
            // Create or update config from legacy settings
            if (dungeonConfig == null)
            {
                dungeonConfig = ScriptableObject.CreateInstance<DungeonConfig>();
            }
            
            // Sync legacy settings to config
            dungeonConfig.columns = columns;
            dungeonConfig.rows = rows;
            dungeonConfig.minRoomSize = minRoom;
            dungeonConfig.maxRoomSize = maxRoom;
            dungeonConfig.density = density;
            dungeonConfig.useSeed = useSeed;
            dungeonConfig.seed = seed;
            
            mapManager.InitializeMap(dungeonConfig);
            LastResult = mapManager.CurrentResult;
            
            Debug.Log("[UnityDungeonTilemapBuilder] Delegated to MapInitializationManager (new system)");
            return true;
        }
        
        /// <summary>
        /// Migrate this GameObject to use new system components.
        /// Call from editor context menu to upgrade.
        /// </summary>
        [ContextMenu("Migrate to New System")]
        private void MigrateToNewSystem()
        {
            #if UNITY_EDITOR
            Debug.Log("[UnityDungeonTilemapBuilder] Starting migration to new system...");
            
            // Create MapInitializationManager if not exists
            if (mapManager == null)
            {
                mapManager = gameObject.AddComponent<MapInitializationManager>();
            }
            
            // Create DungeonConfig asset
            if (dungeonConfig == null)
            {
                dungeonConfig = ScriptableObject.CreateInstance<DungeonConfig>();
                dungeonConfig.columns = columns;
                dungeonConfig.rows = rows;
                dungeonConfig.minRoomSize = minRoom;
                dungeonConfig.maxRoomSize = maxRoom;
                dungeonConfig.density = density;
                dungeonConfig.useSeed = useSeed;
                dungeonConfig.seed = seed;
                
                // Save as asset
                string path = "Assets/Settings/Dungeon/DungeonConfig_Migrated.asset";
                UnityEditor.AssetDatabase.CreateAsset(dungeonConfig, path);
                UnityEditor.AssetDatabase.SaveAssets();
                Debug.Log($"[UnityDungeonTilemapBuilder] Created DungeonConfig at {path}");
            }
            
            useNewSystem = true;
            Debug.Log("[UnityDungeonTilemapBuilder] Migration complete! Enable 'Use New System' to switch.");
            #endif
        }
    }
}


